### ISSUE TITLE
项目运行时报错

### ISSUE THREAD

**Issue by zhishan33** [ohbug-org/ohbug#1]
vue 项目：
This dependency was not found:

* child_process in ./~/node-machine-id/dist/index.js

**Comment by chenyueban** [comment]
> vue 项目：
> This dependency was not found:
> 
> * child_process in ./~/node-machine-id/dist/index.js

请附上运行的环境相关信息 例如：

- 使用的包名称以及版本：`@ohbug/browser` or `@ohbug/vue`
- nodejs 版本
- 操作系统
- 具体的操作流程 例如在 `npm install` 时报错 / `npm install` 正常，启动项目时报错

**Comment by chenyueban** [comment]
已解决
