### ISSUE TITLE
[BUG] docker部署后访问不了

### ISSUE THREAD

**Issue by chasonhuang** [ohbug-org/ohbug#10]
docker部署后访问不了
{"errorMessage":"Cannot GET /","errorCode":50000,"success":false}

**Comment by chenyueban** [comment]
请提供详细些的排错信息。例如操作步骤，环境配置，启动流程等

**Comment by chasonhuang** [comment]
谢谢，端口配置的有问题，已经解决了。
现在起来了，但是检测不到错误，再帮忙看下哪里有问题吗，配置如下：
apiKey填的是创建项目后对应的key
const client = Ohbug.init({
  apiKey: 'b52821c750997fa9fcb8944f74160d9973121a280c245847510a245346dff8e0'
});
const OhbugErrorBoundary = client.use(OhbugReact, React);

下面组件return
<OhbugErrorBoundary>
        {children}
</OhbugErrorBoundary>

**Comment by chasonhuang** [comment]
return (
    <OhbugErrorBoundary>
        {children}
    </OhbugErrorBoundary>
  );

**Comment by chasonhuang** [comment]
![微信截图_20210430101950](https://user-images.githubusercontent.com/26567656/116640645-a64dac80-a99d-11eb-9345-be0bd7566dfe.png)

**Comment by chasonhuang** [comment]
notified可以输出事件，但是事件统计那收不到，帮忙看看什么问题
![image](https://user-images.githubusercontent.com/26567656/116644426-e57ffb80-a9a5-11eb-90c3-316fc6af15af.png)
![image](https://user-images.githubusercontent.com/26567656/116644444-f0d32700-a9a5-11eb-8627-bafee5242739.png)

**Comment by chasonhuang** [comment]
![image](https://user-images.githubusercontent.com/26567656/116646707-5675e200-a9ab-11eb-9af5-b3ecefb5db39.png)
好像是上传报告问题，搞了代理转发到ohbug对应的ip端口下，没起作用

**Comment by chasonhuang** [comment]
![image](https://user-images.githubusercontent.com/26567656/116646847-aa80c680-a9ab-11eb-816c-5921518fe830.png)
这个是ohbug端口配置，这样有问题吗

**Comment by chenyueban** [comment]
> ![image](https://user-images.githubusercontent.com/26567656/116646847-aa80c680-a9ab-11eb-816c-5921518fe830.png)
> 这个是ohbug端口配置，这样有问题吗

6660 是专门用作接收事件的端口，和web服务是分开的，docker-compose配置按照默认的就可以。
可能需要在 ohbug init 时传入上报接口的地址，例如：
```js
const client = Ohbug.init({
	apiKey: 'b52821c750997fa9fcb8944f74160d9973121a280c245847510a245346dff8e0',
	endpoint: 'http://localhost:6660/report',
});
```

**Comment by chasonhuang** [comment]
解决了，感谢大佬^^
