### ISSUE TITLE
/issue只要有上传过错误，界面访问不了，报错

### ISSUE THREAD

**Issue by chasonhuang** [ohbug-org/ohbug#11]
五一前可以正常访问查看错误。
今天突然不行了，重新部署了服务还是不行，换其他服务器又正常的。
帮忙看看是什么问题，实在不行能否帮忙清下我这台服务器的数据，初始化下。ip：81.68.179.85
错误如下：
![image](https://user-images.githubusercontent.com/26567656/117433561-2fe11980-af5e-11eb-823a-33a995e918d3.png)
![image](https://user-images.githubusercontent.com/26567656/117433630-44251680-af5e-11eb-8e34-83f797c79211.png)

**Comment by chenyueban** [comment]
原 docker 镜像删除 拉下最新的版本看看。
