### ISSUE TITLE
收集的bug上传到哪？怎么查看管理收集的bug

### ISSUE THREAD

**Issue by WREQI** [ohbug-org/ohbug#16]

**Comment by chenyueban** [comment]
有配套的 server 部分 需自行部署 https://github.com/ohbug-org/ohbug-server

**Comment by silent-tan** [comment]
server 闭源了吗 ：（

**Comment by chenyueban** [comment]
没有 项目名换了 https://github.com/ohbug-org/ohbug-dashboard

**Comment by silent-tan** [comment]
刚刚看到，抱歉，最好也改下文档 ❀❀❀

**Comment by chenyueban** [comment]
> 刚刚看到，抱歉，最好也改下文档 ❀❀❀

文档都是改了的 只不过这个 issue 是改文档之前就有的

**Comment by silent-tan** [comment]
很久之前关注了这个项目了，很赞，后面想看下后端的思路，直接点进 server 找不到，想加个 issue，发现这个，导航了这了。: )

**Comment by chenyueban** [comment]
> 很久之前关注了这个项目了，很赞，后面想看下后端的思路，直接点进 server 找不到，想加个 issue，发现这个，导航了这了。: )

感谢关注
