### ISSUE TITLE
yarn dev error

### ISSUE THREAD

**Issue by luozhanxin** [ohbug-org/ohbug#2]
1. 使用的包名称以及版本：ohbug 项目
1. nodejs 版本: v12.16.2
1. 操作系统: mac
1. 具体的操作流程 
    1. yarn 
    1. yarn dev 
1. 错误信息
  `` [!] Error: Cannot find module '/Users/xx/git/ohbug-project/ohbug/packages/core/package.json' ``

修改后可以运行：
 1.  scripts/dev.js [5]
``const target = args._.length ? args._ : 'core'``
``const target = args._.length ? args._ : 'ohbug-core'``

**Comment by chenyueban** [comment]
> 1. 使用的包名称以及版本：ohbug 项目
> 2. nodejs 版本: v12.16.2
> 3. 操作系统: mac
> 4. 具体的操作流程
>    
>    1. yarn
>    2. yarn dev
> 5. 错误信息
>    `[!] Error: Cannot find module '/Users/xx/git/ohbug-project/ohbug/packages/core/package.json'`
> 
> 修改后可以运行：
> 
> 1. scripts/dev.js [5]
>    `const target = args._.length ? args._ : 'core'`
>    `const target = args._.length ? args._ : 'ohbug-core'`

感谢关注 Ohbug.

问题已经收集到，下个版本就可以进行修复。
