### ISSUE TITLE
[BUG] vue 项目 yarn serve  启动时编译错误

### ISSUE THREAD

**Issue by ysneo** [ohbug-org/ohbug#24]
![image](https://user-images.githubusercontent.com/17615113/182269587-645ae0b0-31b5-40be-a425-98ff06e607eb.png)

启动时一直提示这个错

- OS: windows
- Version :
![image](https://user-images.githubusercontent.com/17615113/182269618-a1f411ee-f663-4c8a-9793-3ddd3f08569b.png)

**Additional context**

**Comment by ysneo** [comment]
vue cli 4但是不解析 mjs?
![Uploading image.png…]()

**Comment by ysneo** [comment]
vue 2 支持吗?

**Comment by chenyueban** [comment]
```js
// vue2
import Vue from "vue";
import App from "./App.vue";
import Ohbug from "@ohbug/browser";
import OhbugVue from "@ohbug/vue";

const client = Ohbug.setup({ apiKey: "YOUR_API_KEY" });
OhbugVue(client).install(Vue);

new Vue({
  render: (h) => h(App)
}).$mount("#app");

```

**Comment by ysneo** [comment]
still has problem
![image](https://user-images.githubusercontent.com/17615113/182525131-12de4b1f-aebb-44b2-8b32-5938a9fcc946.png)
[Vue2Template.zip](https://github.com/ohbug-org/ohbug/files/9248379/Vue2Template.zip)

**Comment by chenyueban** [comment]
update `@ohbug/browser` to version `2.1.2` and `@ohbug/vue` to version `2.0.8`.

**Comment by ysneo** [comment]
no this version 
![image](https://user-images.githubusercontent.com/17615113/182546774-94e1b2db-5cd5-4e22-b117-a0bc024d907a.png)

**Comment by ysneo** [comment]
good
![image](https://user-images.githubusercontent.com/17615113/182550232-1ccd247a-f548-4b8a-8239-4bf6c110337c.png)
