### ISSUE TITLE
How does one change their on-prem ohbug account password after user creation?

### ISSUE THREAD

**Issue by darkvertex** [ohbug-org/ohbug#26]
So I noticed the first time you login you can make an account, but then there seems to be no clear way to reset the password.

How does one do that? Do I need to hack into the postgres db for that?

**Comment by chenyueban** [comment]
As of now, there is no way to directly modify the password.
If you need to modify the password, you need to connect to the database to modify the password.
Of course, I will add the entrance to modify the password in the next version.
