### ISSUE TITLE
SDK for Angular？

### ISSUE THREAD

**Issue by HavoStrean** [ohbug-org/ohbug#3]
Hi, is SDK for Angular is in the plan?
你好，是否有计划安排开发SDK for Angular？

**Comment by chenyueban** [comment]
> Hi, is SDK for Angular is in the plan?
> 你好，是否有计划安排开发SDK for Angular？

你好 感谢关注 Ohbug.

Angular 这块已经在规划，预计最近就可以进入开发阶段了

**Comment by chenyueban** [comment]
[feat(angular): join @ohbug/angular extension pack](https://github.com/ohbug-org/ohbug/commit/456b1eda44ed9809df37606ae37a0933a6ed592c)
