### ISSUE TITLE
[BUG]在vue中引入ohbug

### ISSUE THREAD

**Issue by zy0228** [ohbug-org/ohbug#4]
**Describe the bug**
我尝试在我的一个vue项目中使用ohbug/vue。当我的project抛出异常错误的时候, 我在问题列表中并没有看到反馈，尝试了多次依然没有收到问题反馈。是我使用的方式不对吗？

**To Reproduce**
1. 我在vue中尝试引入ohbug
```
import Vue from 'vue'
import Ohbug from '@ohbug/browser'
import OhbugVue from '@ohbug/vue'

const client = Ohbug.init({
  apikey: 'xxxxx'
})

client.use(OhbugVue, Vue)
```

2.在浏览器调试栏中可以看到ohbug也捕获到了err
3.在ohbug的管理平台上的项目列表查看并没有任何问题反馈

**Comment by chenyueban** [comment]
```
const client = Ohbug.init({
  apikey: 'xxxxx'
})
```
我注意到你这里 apikey 属性打错了，应该是大写 K `apiKey`。
检查一下你的代码是存在同样的问题哦

**Comment by zy0228** [comment]
oh,好吧...哈哈,确实是这样
